#.. _____________________ ..#
## -- // WARNING \\ -- 
## -- THIS WORK IS UNDER EXCLUSIVE COPRIGHT FOR BAITCORP LABS. DISTRIBUTION, MODIFICATION, SELLING, OR SHARING WITHOUT EXPLICIT PERMISSION FROM BAITCORP LABS IS STRICTLY PROHIBITED.
## -- THIS PROGRAM IS LICENSED FOR MODIFICATION TO AND ONLY TO: "BAITCORP LABS" [FR], "CCHOST PARIS" [FR].
## -- 
## -- ExploitsX Sebastian Giheta 2019-2020
#.. _____________________ ..#

#.. _____________________ ..#
# ___________              .__         .__  __         ____  ___              _________ .__            __   _________         
# \_   _____/__  _________ |  |   ____ |__|/  |_  _____\   \/  /     .__      \_   ___ \|  |__ _____ _/  |_ \_   ___ \  ____  
#  |    __)_\  \/  /\____ \|  |  /  _ \|  \   __\/  ___/\     /    __|  |___  /    \  \/|  |  \\__  \\   __\/    \  \/ /  _ \ 
#  |        \>    < |  |_> >  |_(  <_> )  ||  |  \___ \ /     \   /__    __/  \     \___|   Y  \/ __ \|  |  \     \___(  <_> )
# /_______  /__/\_ \|   __/|____/\____/|__||__| /____  >___/\  \     |__|      \______  /___|  (____  /__|   \______  /\____/ 
#         \/      \/|__|                             \/      \_/                      \/     \/     \/              \/        
#
# ExploitsX by Sebastian Giheta, owner of 8b8t.xyz
#.. _____________________ ..#



#.. _____________________ ..#
#.. _______SECTION_______ ..#
#.. ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ..#
#....... PATCH NOTES .......#
#.. ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ..#
#.. ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ..#
#.. ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ..#

#... Development settings ..#
# keep debug false unless you love reading console spam
debug: false
# keep ExploitsX cool. If you don't want anybody to see you have ExploitsX installed,
# you can set this to false (not recommended, might be confusing if you're trying to find the
#   cause of a bug.)
branding: true
# extra logging on startup. choose between levels 0 and 2.
logging-level: 2
#.. _____________________ ..#

#... Exploits/bugs/fixed ...#
# skylight lag - piston retract, piston push, block break, block place
# portal lag - nether item, end item, gateway item
# redstone lag - cancelling and removal
# wither lag - disable wither spawning on set tps
# TPS monitor - limits tnt, pistons, elytra (Get RoofPatch for more protection)
# minecart lag / crash - minecart cramming
# teleport crash
# donkey world changement crash
# infinite pig reach
# infinite pig speed (only teleporting variant)
# teleport location tracking
# map overload
# EndCrystal lag patches
# sand lag
# 32k pickaxe crash
# entity spam
# entity cramming
# highest-tier spambot prevention (when paired with Xantibot)
# container-spam lag/crash
# punch-spam lag
# some precautionary measures for illegal items
# tnt lag
# location packet lag (including some blink modules)
# spawn eggs
# village / fortress generation lag
#.. _____________________ ..#

#......... COMMANDS ........#
# /ex (or /ex version): Display your current version of ExploitsX
# /ex reload: Reload ExploitsX configuration
# /stats <player>: get a player's stats
# /xitem (for testing purposes, this is OP-ONLY and will spawn a shulker with items you want in it. Used for testing the antibookban and a few patches so use as you wish.)
#   - usage: /xitem (shulker box bukkit name) (item bukkit name) (durability)
#   - example: /xitem RED_SHULKER_BOX WRITTEN_BOOK 0 
# /donate
# /chatco
# /tell, /msg, /ignore, all chat functionality + color formatting
# /discord
# /donate
# /pl
#.. _____________________ ..#

#..... GAMEPLAY CHANGES ....#
# full chatco plugin with error fixes, configuration handling changements and memory leak fixes
# tp - disables tp's in a set boundary around spawn
# wither lag - limits high amounts of withers
# WIP antispam
# item lag - lots of items in a spot lagging
# antibookban - even previously banned players will be fixed
# offhand fixes
# illegal item fix (soft patches for servers like 8b8t)
# anti redstone
# full statistics saving system
# /pl modification
# /discord modification
# /donate modification
# spawn radius for teleportation (can be disabled)
#.. _____________________ ..#

#..... ABUSE PROTECTION ....#
# /op prevention
# opped whitelist
# creative whitelist
# blocked commands
# console blocked commands
#.. _____________________ ..#

#....... PLACEHOLDERS ......#
# %ef-tps%: Live Server TPS
# %ef-online%: Live Playercount
# %ef_uptime%: Live Server Uptime
#.. _____________________ ..#



#.. _____________________ ..#
#.. _______SECTION_______ ..#
#.. ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ..#
#...... CONFIGURATION ......#
#.. ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ ..#
#.. ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ..#
#.. ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾ ..#

#...........................#
#..... GAMEPLAY CHANGES ....#
#...........................#
# announce reload of ExploitsX to the server (because this plugin sometimes causes lag if reloaded with many people online)
#   keep false unless people are wondering where the lag is from / you want to look cool and show people you have this plugin.
announcereloads: false
# spawn radius in blocks to block teleportations from /tpa, /back, /home etc.
sr: 0
# dynamically change your TPS. set this to 0 to disable
# this will make the TPS appear higher than what it actually is. Only use for social experiments.
# keeping this at 1 is a good idea because of many misconceptions that 19 tps is bad.
addtotps: 1
# Join / Leave messages
enablejoinleavemsg: true
# disable the join/leave messages if the player count is above this amount.
joinleavemsgdisable: 40
# clear fortress data on exit? This is EXTREMELY recommended for servers. No noticeable changes and your server also doesn't die
clearvillagedata: true
# name of your main world. By default it's "world"
clearworldname: world
#...........................#
#.. _____________________ ..#
#...........................#

#...........................#
#..... COMMANDS CONFIG .....#
#...........................#
#
## VV /pl command VV #
# enable /pl spoofing
plspoof: true
# enable 8b8t's /pl spoof (for 8b8t.xyz's use only)
8b8tpl: false
# customize your /pl list.
# you can disable the prefix or suffix by setting them to "disable"
plprefix: "Here are my server's plugins!"
plmessage: "Plugins(0): &a&lNone-of-your-business"
plsuffix: "&cPowered by ExploitsX"
#
## VV /donate command VV #
donatecommand: true
donatemessage: "&a- Thank you for considering to donate. You may do so at https://paypal.me/baitdonate/ or https://8builders.tebex.io/ -"
#
## VV /discord command VV #
discordcommand: false
discordmessage: "&a- Join our discord! https://discord.gg/BEHBf7J -"
#
## VV Stats Command VV #
# enable data saving for statistics
statssavedata: true
# enable the /stats command and all of it's cool features
statsenable: true
# save movement packets to statistics (might be doing a lot of read/writes to the ram. Keep false if you have 100+ players)
statslogmovementscore: true
#...........................#
#.. _____________________ ..#
#...........................#

#...........................#
#..... SYSTEM CLOCKS .......#
#...........................# 
# do not change any value in here unless you know exactly what this is about. Default values are perfect.
# delay to remove 1 from violationmap. Keep this at 15-20 unless you know what you're doing
# measured in ticks
vlremovedelay: 15
# don't change the next value unless ExploitsX is severely throttling your startup time when loading violationmaps
#   on plugin reloads.
vlremovedelaystartupby: 10
#...........................#
#.. _____________________ ..#
#...........................#

#...........................#
#..... EXPLOIT FIXES .......#
#...........................# 
# Skylight lag patch
skylight: true
# y level to check for rogue pistons
ylevel: 250
#check-surroundings is to reduce the amount of false positives. Uses 3-8% more CPU (high reward) to do these checks.
check-surroundings: true
# stop pistons from creating lightlag (band-aid fix, might need tweaking.)
patch-piston: true

# Cancel non-player entities going through portals
portal: true
# Cancel non-player entities going through end gateways
gateway: true
# Chunk ban fixes
patchchunkban: true
# max entities when checking for item frame placement
ifentitymax: 300
# max chests, shulkers etc.
tileentitymax: 400
# max skulls
skullmax: 80
chunkbanmsg: "&6Chunk bans are prohibited."
chunkbanitemframemsg: "&6Item frames are limited in each chunk."
# book ban settings
# don't set this to false, the system is very good and doesn't need to be disabled.
enableantibookban: true
# cancel players from picking up items with too many books (DEPRECATED, keep true until this is removed)
cancelpickup: true

# teleport fixes
# disable teleports while riding (infinite reach, infinite speed, crashserver fix, little gameplay changement.)
disable-riding-teleport: true
# fix teleportation tracking exploit (might break some /back plugins, should work with essentials fine.)
teleport-exploit-patch: true

# enable anti map spam
mapspampatch: true
# amount of maps to trigger anti map spam
mapspamincrement: 6
# clear a player's violations on leave. This means they can relog after if theyre getting blocked from using maps
mapclearleave: true
#...........................#
#.. _____________________ ..#
#...........................#


#...........................#
#........ LAG FIXES ........#
#...........................#
# Set all values below this to 0 in order to disable the module
# Disabling based on tps 
# vdouble is max speed (blocks / movement packet) while elytras are disabled
elytraint: 12
vdouble: 0.6
tntint: 10
pistonint: 15
witherspawn: 8
# prevent note blocks below this value
note-tps: 17.5
note-remove: 13.5
# TPS to cancel redstone
redcancel: 15
# TPS to remove redstone (including whole machines) (ignores trapped chests)
redremove: 10
#...........................#
#.. _____________________ ..#
#...........................#


#...........................#
#....... RATE LIMITS .......#
#...........................#
interact-limit: true
## set these values over 100 to disable ##
# prevent players from spamming chests or tools to lag the server.
# counted for each second
interact-cancel: 7
interact-kick: 30
#
# VV Entity Limits VV #
# max withers in a 64 block radius
maxwithers: 96
# max items in a 64 block radius
Item-per-region.limit: 200
Vehicle-per-chunk.limit: 16
# light lag fixes
# it'll take 15 light-intensive block actions to warn the player
skylight-warn: 15
# it'll take 20 light-intensive block actions to cancel actions that are 
skylight-cancel: 20
# it'll take 30 light-intensive block actions to kick
skylight-kick: 30
#...........................#
#.. _____________________ ..#
#...........................#


#...........................#
#..... ITEM PROTECTION .....#
#...........................#
# This is a basic item restriction system. Made for servers like 8b8t.xyz that
# likes certain unobtainable items but wants to get rid of a few.
#
# Enable item restriction (and item stacking limits)
itemrestriction: true
# Enable armor checking?
# armorcheckdelay is in ticks, multiply seconds by 20 to get this amount (100 ticks is 5 seconds) (keep above 10)
armorcheck: true
armorchecktickdelay: 80
# patch higher efficiency pickaxes without patching other enchants (useful to slow down skylight lag)
patch-efficiency: true
# Items which are limited by a max stack size
limited-items:
 - TOTEM
maxstacksize: 48
# deny spawn eggs
denyeggs: true
# Blocked Lores
# Players cannot hold these items in their inventories if their lores match this (useful for 8b8t.xyz)
lore-list:
 - III The Mighty Chest III
 - Ooh, Scary!
 - eh why not :D
# Exempt Players from item restriction
exempt-list:
 - Iz_Da_Bait
 - _____________0__
# Messages
Skylight-lag-message: "Please do not attempt this."
Offhand-Server-Crash.Book-message: "Sorry, Offhanding a book is not allowed here."
Offhand-Server-Crash.Shulker-message: "Sorry, Offhanding a crash shulker is not allowed here."
#...........................#
#.. _____________________ ..#
#...........................#


#...........................#
#..... CHAT PROTECTION .....#
#...........................#
log-commands: false
# enable chat filter 
chatfilter: true
# use AI to detect malicious messages (recommended)
chat-useAI: true
# decimal 0-1 to describe similar messages to cause red flags.
# recommended at 0.7, this means if a message is 70+% close to another that a player sent it will be marked as spam.
chat-AI-similarity: 0.7
# log violations (to console)
log-flags: true
# bot captcha server (contact Bait#8888 about this if you're unsure)
# NOTICE:
# if you don't want to install / don't have a separate server with Xantibot installed, you don't need to worry about this.
# this just adds a small layer of security that won't really be noticeable if you don't enable it.
# leave it to "auth" or "false" if you don't have one.
antibot-server: auth
antibot-message: "&6ExploitsX &4thinks you're spamming... &4(Try turning off your chat modifications or spammers)"
# cancel message on this amount of violations
cancel-point: 7
# send to auth server on this amount of violations
tipping-point: 11
# kick players at this violation
kick-point: 15
# punish players by cancelling their event if they're inbetween cancel and tipping point EVEN if message is not flagged
punish-player: true
# clear violations on leave (recommended: false)
# this automatically clears every interval-period to clear memory leaks
leave-clear: false
# interval in seconds to clear hashmaps (if you have 16+ gb of ram keep this at 43200 for a good experience)
clear-interval: 43200
# by default we added a few well-known chatbots that don't spam
chat-exempt:
 - Saldonia
 - moooomoooo
 - c8nt
 - AnarchyB0T
# alert admins on chat violations (may be spammy)
alert-to-admins: false
# these words can absolutely not be sent in chat. Be cautious with this.
blacklisted-words:
 - 123.123.123.123
 - yourrealname
# add to a player's violation count if they say the message aswell as cancelling it. Set this to a high number to 
# essentially mute them until the clear-interval passes.
blacklist-vladd: 4
#
#
# >>> check config2.yml for more configuration and red flag words, and check chatco.yml for chatco settings.
#...........................#
#.. _____________________ ..#
#...........................#


# Don't change the next line unless you're updating the config!
confversion: 446